
from data.generators.task_generator.arc_task_generator import ARCTask
from data.generators.object_recognition.basic_geometry import Dimension2D, Point
from dsls.our_dsl.functions import task_solving_utils as utils
from dsls.our_dsl.solutions import solutions as sols

task = ARCTask('97a05b5b')
task.generate_canvasses()

unique_objects = [
    {'primitive': 'Random', 'colour': 1, 'id': 0, 'actual_pixels_id': 0, 'dimensions': Dimension2D(9, 17),
     'canvas_and_position': [0, Point(2, 6, 0)],
     'actual_pixels': task.get_object_pixels_from_data(0, Point(2, 6, 0), Dimension2D(9, 17)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 1, 'actual_pixels_id': 1, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [0, Point(3, 1, 0)],
     'actual_pixels': task.get_object_pixels_from_data(0, Point(3, 1, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 2, 'actual_pixels_id': 2, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [0, Point(8, 1, 0)],
     'actual_pixels': task.get_object_pixels_from_data(0, Point(8, 1, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 3, 'actual_pixels_id': 3, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [0, Point(14, 4, 0)],
     'actual_pixels': task.get_object_pixels_from_data(0, Point(14, 4, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 4, 'actual_pixels_id': 4, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [0, Point(14, 14, 0)],
     'actual_pixels': task.get_object_pixels_from_data(0, Point(14, 14, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 5, 'actual_pixels_id': 5, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [0, Point(13, 19, 0)],
     'actual_pixels': task.get_object_pixels_from_data(0, Point(13, 19, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 6, 'actual_pixels_id': 6, 'dimensions': Dimension2D(8, 8),
     'canvas_and_position': [2, Point(1, 11, 0)],
     'actual_pixels': task.get_object_pixels_from_data(2, Point(1, 11, 0), Dimension2D(8, 8)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 7, 'actual_pixels_id': 7, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [2, Point(1, 6, 0)],
     'actual_pixels': task.get_object_pixels_from_data(2, Point(1, 6, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 8, 'actual_pixels_id': 8, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [2, Point(5, 4, 0)],
     'actual_pixels': task.get_object_pixels_from_data(2, Point(5, 4, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 9, 'actual_pixels_id': 9, 'dimensions': Dimension2D(9, 9),
     'canvas_and_position': [4, Point(1, 1, 0)],
     'actual_pixels': task.get_object_pixels_from_data(4, Point(1, 1, 0), Dimension2D(9, 9)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 10, 'actual_pixels_id': 10, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [4, Point(5, 12, 0)],
     'actual_pixels': task.get_object_pixels_from_data(4, Point(5, 12, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 3, 'id': 11, 'actual_pixels_id': 11, 'dimensions': Dimension2D(12, 8),
     'canvas_and_position': [6, Point(2, 10, 0)],
     'actual_pixels': task.get_object_pixels_from_data(6, Point(2, 10, 0), Dimension2D(12, 8)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 12, 'actual_pixels_id': 12, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [6, Point(1, 5, 0)],
     'actual_pixels': task.get_object_pixels_from_data(6, Point(1, 5, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 13, 'actual_pixels_id': 13, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [6, Point(3, 0, 0)],
     'actual_pixels': task.get_object_pixels_from_data(6, Point(3, 0, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 12, 'actual_pixels_id': 12, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [6, Point(8, 5, 0)],
     'actual_pixels': task.get_object_pixels_from_data(6, Point(8, 5, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
    {'primitive': 'Random', 'colour': 1, 'id': 12, 'actual_pixels_id': 12, 'dimensions': Dimension2D(3, 3),
     'canvas_and_position': [6, Point(11, 1, 0)],
     'actual_pixels': task.get_object_pixels_from_data(6, Point(11, 1, 0), Dimension2D(3, 3)),
     'on_canvas_transformations': [],
     'in_out_transformations': [],
     'symmetries': []},
]


task.generate_objects_from_output(unique_objects=unique_objects)
task.reset_object_colours()

example = utils.solve_canvas_pairs(task=task, solution=sols.solution_97a05b5b, which_pair='all')

example.show()


